source "https://rubygems.org"
gemspec

gem "jekyll", "~> 4.2"
gem "just-the-docs", "~> 0.12.0"

gem "jekyll-include-cache", group: :jekyll_plugins

gem 'jekyll-redirect-from'

gem 'wdm', '>= 0.2.0' if Gem.win_platform?

gem "webrick", "~> 1.9"
