# Copyright (c) Laserfiche.
# Licensed under the MIT License. See LICENSE in the project root for license information.

require 'html-proofer'


task :htmlproof do
  sh "bundle exec jekyll build"
  options = { :ignore_urls => "/.*https?.*/" }
  HTMLProofer.check_directory('_site/', opts = {
    :ignore_urls => ["/https?/"]
  }).run
end

task default: %w[htmlproof]