# © 2026 Laserfiche.
# See LICENSE-DOCUMENTATION and LICENSE-CODE in the project root for license information.

require 'html-proofer'


task :htmlproof do
  sh "bundle exec jekyll build"
  HTMLProofer.check_directory('_site/', opts = {
    # :ignore_urls => [/https?:(?!(.*developer\.laserfiche\.com.*))/], # ignore all external URLs EXCEPT for developer.laserfiche.com
    :ignore_urls => [/https?/] # ignore all external urls
  }).run
end

task default: %w[htmlproof]